x <- readline(prompt='x1 = ')
y <- readline(prompt='x2 = ')
fexpr <- readline(prompt='f(x) = ')
fxunsolved <- gsub('x', x, fexpr, ignore.case = TRUE)
fyunsolved <- gsub('x', y, fexpr, ignore.case = TRUE)
fxsolved <- parse(text = fxunsolved)
fysolved <- parse(text = fyunsolved)
fxresult <- eval(fxsolved)
fyresult <- eval(fysolved)
print(paste('{ x1 , f(x1) } = {',x,',',fxresult,'}'))
print(paste('{ x2 , f(x2) } = {',y,',',fyresult,'}'))
xysize <- readline(prompt = 'X axis and Y axis size is: ')
xysize = as.integer(xysize)
xysizeneg <- xysize*-1
xysizepos <- xysize
flineneg <- xysizeneg*100000
flinepos <- xysizepos*100000
x = as.integer(x)
y = as.integer(y)
xysizenegint = as.integer(xysizeneg)
xysizeposint = as.integer(xysizepos)
plot(c(x,y,0), c(fxresult,fyresult,0), xlim=c(xysizeneg, xysizepos), ylim=c(xysizeneg, xysizepos), xlab = 'X', ylab = 'Y')
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted", lwd = par("lwd"), equilogs = TRUE)
segments(x0 = x, y0 = fxresult, x1 = y, y1 = fyresult, col = "red", lwd = 2)
segments(x0 = flinepos, y0 = 0, x1 = flineneg, y1 = 0, col = "black")
segments(x0 = 0, y0 = flineneg, x1 = 0, y1 = flinepos, col = "black")
segments(x0 = y, y0 = fyresult, x1 = 0, y1 = fyresult, col ="blue", lty = "dotted", lwd = 2)
segments(x0 = y, y0 = fyresult, x1 = y, y1 = 0, col ="blue", lty = "dotted", lwd = 2)
segments(x0 = x, y0 = fxresult, x1 = 0, y1 = fxresult, col ="blue", lty = "dotted", lwd = 2)
segments(x0 = x, y0 = fxresult, x1 = x, y1 = 0, col ="blue", lty = "dotted", lwd = 2)
